development:
  adapter: postgresql
  encoding: unicode
  database: eshop_development
  username: postgres
  password: root
  pool: 100
  
production:
  adapter: postgresql
  encoding: unicode
  database: eshop_development
  username: postgres
  password: root
  pool: 100